

version: "3.7"
services:
  oriundb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: ${DATABASE_RESTART:-no}
    container_name: oriundb
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_TCP_PORT: ${DATABASE_PORT}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - ${DATABASE_PORT:-3306}:${DATABASE_PORT:-3306}
  prisma-mysql-api:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prisma-mysql-api
    depends_on:
      - oriundb
    ports:
      - "4000:4000"
    restart: always
volumes:
  db_data:
