

version: "3.7"
services:
  oriundb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: ${DATABASE_RESTART:-no}
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_TCP_PORT: ${DATABASE_PORT}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - ${DATABASE_PORT:-3306}:${DATABASE_PORT:-3306}
volumes:
  db_data:
